backend:
  name: git-gateway
  branch: master

local_backend: true
# > npx netlify-cms-proxy-server

media_folder: assets/uploads
public_folder: /uploads

collections:

  - name: articles
    label: Artikel
    summary: "{{date | date('YYYY-MM-DD')}} - {{title}} - {{source}}"
    folder: content/articles
    create: true
    fields:
      - label: Titel
        name: title
        widget: string
      - label: Link
        name: link
        widget: string
        required: false
      - label: Veröffentlicht
        name: date
        widget: date
        date_format: 'DD.MM.YYYY'
      - label: Quelle
        name: source
        widget: string
      - label: Bild
        name: image
        widget: image
      - name: "sitemap_exclude"
        widget: hidden
        default: true

  - name: team
    label: Künstler
    folder: content/team
    create: false
    fields:
      - label: Name
        name: title
        widget: string
      - label: Bild
        name: image
        widget: image
      - label: Gast
        name: guest
        widget: boolean
        required: false
      - label: Stücke
        name: plays
        widget: select
        multiple: true
        options: ['ein-einziger-tag', 'naumbalo', 'GemEinsam', 'gedankenträume']
      - label: Text
        name: body
        widget: markdown

  - label: Seiten
    name: pages
    files:
      - label: Über uns
        name: about
        file: data/about.yaml
        fields:
          - label: Titel
            name: title
            widget: string
          - label: Kurz
            name: short_text
            widget: markdown
          - label: Lang
            name: long_text
            widget: markdown

      - label: Impressum
        name: impress
        file: content/pages/imprint.md
        fields:
        - label: Titel
          name: title
          widget: string
        - label: Text
          name: body
          widget: markdown
        - name: "sitemap_exclude"
          widget: hidden
          default: true

  - name: play
    label: Stücke
    folder: content/plays
    create: true
    fields:
      - label: Titel
        name: title
        widget: string
      - label: Bild
        name: image
        widget: image
      - label: Sortierung
        name: weight
        widget: number
        value_type: int
        min: -10
        max: -1
        step: 1
      - label: Bilder
        name: images
        widget: list
        summary: '{{fields.image}}'
        field:
          label: Image
          name: image
          widget: image
      - label: Text
        name: body
        widget: markdown

  - name: event
    label: Termine
    folder: content/events
    create: true
    sortable_fields: ['eventDate']
    summary: "{{eventDate | date('YYYY-MM-DD')}}: {{title}}"
    fields:
      - label: Titel
        name: title
        widget: string
      - label: Datum
        name: eventDate
        widget: datetime
        format: YYYY-MM-DDTHH:mm:00Z
        date_format: 'DD.MM.YYYY'
        time_format: 'HH:mm'
        picker_utc: false
      - label: Veranstaltungsort
        name: location
        widget: string
      - label: Link
        name: link
        widget: string
        required: false
      - label: Text
        hint: Nur sichtbar für Veranstaltungen ohne Link
        name: body
        widget: markdown
        required: false

