baseURL = "https://talomini.de/"
languageCode = "de-de"
title = "Junges Musiktheater"

[permalinks]
  pages = "/:slug/"
  team = "/:slug/"

[params.meta]
  favicon = "favicon.ico"

[params]
    description = "Das Saarbrücker Musiktheaterensemble vereint Gesang, Tanz, Instrumentalspiel und Szene in liebevollen Stücken für alle von 3 bis 99 Jahren."
    images = ["images/banner.jpg"]

    [params.homepage]
        sections = [ "home", "about", "contact", "imprint" ]

    [params.navigation]
        brand = "Junges Musiktheater Talomini"
        [params.navigation.links]
            about    = "Über uns"
            contact  = "Kontakt"
            imprint  = "Impressum"


    # ----------

    # PAGE 404
    [params.page404]
        text = "OOPS, PAGE NOT FOUND!"
        background_image = "404.jpg"
        button_text = ""

