baseURL = "https://talomini.de/"
languageCode = "de-de"
title = "Junges Musiktheater Talomini"

metaDataFormat = "yaml"
enableRobotsTXT = true

[permalinks]
  pages = "/:slug/"
  plays = "/:slug/"
  team = "/:slug/"

[params]
  preview = false
  description = "Das Saarbrücker Musiktheaterensemble vereint Gesang, Tanz, Instrumentalspiel und Szene in liebevollen Stücken für alle von 3 bis 99 Jahren."

[params.meta]
  favicon = "favicon.ico"

[[params.section]]
  key   = "home"
  label = "Home"

[[params.section]]
  key   = "about"
  label = "Über uns"
  link  = "#ueber-uns"

[[params.section]]
  key   = "plays"
  label = "Stücke"
  link  = "#stuecke"

[[params.section]]
  key   = "events"
  label = "Termine"
  link  = "#termine"

[[params.section]]
  key   = "contact"
  label = "Kontakt"
  link  = "#kontakt"

[[params.section]]
  key   = "press"
  label = "Presse"
  link  = "/presse/"
  preview = true

[[params.section]]
  key   = "imprint"
  label = "Impressum"
  link  = "/impressum/"

[markup]
  defaultMarkdownHandler = "goldmark"

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
