baseURL = "https://talomini.de/"
languageCode = "de-de"
title = "Talomini"

[permalinks]
  pages = "/:slug/"

[params]
    [params.homepage]
        sections = [ "home", "about", "contact", "imprint" ]

    [params.navigation]
        brand = "Junges Musiktheater Talomini"

        # NAVIGATION MENU ENTRIES (OPTIONAL)
        # Add an entry for each section to add in the navigation menu.
        # Syntax:
        #    key = "<VALUE>"
        #    => Where
        #        - "key" is in:
        #            - about
        #            - services
        #            - skills
        #            - projects (! - SPECIAL CASE: DIFFERENT MANAGEMENT THAN OTHER SECTIONS!)
        #            - contact
        #
        #        - "<VALUE>" is the string to display as menu item.
        # If no entry is specified => No navigation menu is created.
        #    (even if "params.navigation.links" is defined, but empty)
        # => Can define a dummy variable in "links" to force the creation of the menu (e.g.: dummy = 1).
        # To change order, need to change code in navigation menu creation.
        # Special case: "projects".
        #    projects = [ { section = "<SECTION_DIRECTORY>", label = "<VALUE>" }, ... ]
        # ! - Values for "sections" in "projects" must be the same as used in "projects.params".
        # (& must correspond to the section directories)
        [params.navigation.links]
            about    = "Über uns"
            contact  = "Kontakt"
            imprint  = "Impressum"


    # ----------

    # PAGE 404
    [params.page404]
        text = "OOPS, PAGE NOT FOUND!"
        background_image = "404.jpg"
        button_text = "BACK HOME"

