baseURL = "https://talomini.de/"
languageCode = "de-de"
title = "Junges Musiktheater Talomini"

metaDataFormat = "yaml"
enableRobotsTXT = true

[permalinks]
  pages = "/:slug/"
  plays = "/:slug/"
  team = "/:slug/"

[params.meta]
  favicon = "favicon.ico"

[params]
    description = "Das Saarbrücker Musiktheaterensemble vereint Gesang, Tanz, Instrumentalspiel und Szene in liebevollen Stücken für alle von 3 bis 99 Jahren."

    [params.homepage]
        sections = [ "home", "about", "plays", "events", "contact", "press", "imprint" ]

    [params.navigation]
        [params.navigation.links]
            about    = "Über uns"
            plays    = "Stücke"
            events   = "Termine"
            contact  = "Kontakt"
            press    = "Presse"
            imprint  = "Impressum"

[markup]
  defaultMarkdownHandler = "goldmark"

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
