[context.production]
  command = "hugo --baseURL https://talomini.netlify.app/"

[context.preview]
  command = "hugo --config config.toml,config.preview.toml --baseURL https://talomini.netlify.app/"

